dist: xenial
sudo: false
notifications:
  email: false
language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm test
jobs:
  include:
    - stage: Release
      node_js: "10"
      script: skip
      after_success:
        - npx semantic-release
branches:
  only:
    - master
